# Generated by Django 5.2.6 on 2025-09-28 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulação', models.CharField(choices=[('M', 'Mestre'), ('D', 'Doutor'), ('P', 'Pós-Doutor')], max_length=1)),
                ('area_pesquisa', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.CharField(max_length=200)),
                ('data_defesa', models.DateField()),
                ('arquivo', models.FileField(upload_to='monografias/')),
                ('status', models.CharField(choices=[('R', 'Rascunho'), ('E', 'Em Defesa'), ('A', 'Aprovada'), ('R', 'Reprovada')], default='R', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmonografias.aluno')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coorientacoes', to='appmonografias.professor')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='appmonografias.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmonografias.monografia')),
                ('professores_avaliadores', models.ManyToManyField(to='appmonografias.professor')),
            ],
        ),
    ]
