# Generated by Django 5.2.6 on 2025-09-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banca',
            name='horario',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='banca',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10),
        ),
    ]
