# Generated by Django 5.2.6 on 2025-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0002_banca_horario_banca_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='banca',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='AGENDADA', max_length=10),
        ),
    ]
