# Generated by Django 5.2.6 on 2025-09-28 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0003_alter_banca_horario_alter_banca_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='nota_final',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
