# Generated by Django 5.2.6 on 2025-09-28 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0004_alter_banca_nota_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='nota_final',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
