# Generated by Django 5.2.6 on 2025-09-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0005_alter_banca_nota_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='status',
        ),
    ]
