# Generated by Django 5.2.6 on 2025-09-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0006_remove_monografia_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='data_defesa',
        ),
    ]
